### ISSUE TITLE
Is it a realtime method?

### ISSUE THREAD

**Issue by QiuZuowei** [ipl-uw/AIC23_Track1_UWIPL_ETRI#1]
Hi, thanks for your great work. Does this system support processing online video streams? If I want to test an input video from the camera, how should I do?

**Comment by yangchris11** [comment]
Hi @QiuZuowei,

Thank you for your interests in our work. Our method for the AICity Challenge is an offline method and do not support realtime tracking for video streaming from camera.

However, we are working on an online version of our work , please stay tune!

Chris

**Comment by FrankMMMMMM** [comment]
@yangchris11 
Hello
Is there a real-time method currently available? Is it open source? Thank you for your reply.
