### ISSUE TITLE
Inference error with one of the validation videos

### ISSUE THREAD

**Issue by vishalsingh-11** [ipl-uw/AIC23_Track1_UWIPL_ETRI#10]
I am trying to perform inference on one of the scenes from the validation set and I am getting the following error when I execute tools/aic_get_detection_syn.py

`Loads checkpoint by local backend from path: work_dirs/yolov7_market/epoch_10_S003_market.pth
The model and loaded state dict do not match exactly

size mismatch for bbox_head.head_module.convs_pred.0.1.weight: copying a param with shape torch.Size([18, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 320, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.0.1.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).
size mismatch for bbox_head.head_module.convs_pred.0.2.implicit: copying a param with shape torch.Size([1, 18, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 255, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.weight: copying a param with shape torch.Size([18, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 640, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).
size mismatch for bbox_head.head_module.convs_pred.1.2.implicit: copying a param with shape torch.Size([1, 18, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 255, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.weight: copying a param with shape torch.Size([18, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 1280, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).
size mismatch for bbox_head.head_module.convs_pred.2.2.implicit: copying a param with shape torch.Size([1, 18, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 255, 1, 1]).
/data/rbondili/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
/data/rbondili/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.TensorboardVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
processing scene S005
Traceback (most recent call last):
  File "tools/aic_get_detection_syn.py", line 158, in <module>
    main()
  File "tools/aic_get_detection_syn.py", line 106, in main
    images = sorted(list_full_paths(os.path.join(input, scene, cam, 'img')))
  File "tools/aic_get_detection_syn.py", line 20, in list_full_paths
    return [os.path.join(directory, file) for file in os.listdir(directory)]
FileNotFoundError: [Errno 2] No such file or directory: '../data/test/S005/c025/img'`

Should I extract frames to create the img/ before I could do the inference ? if so how do I extract the frames I could not see any img/  dir in scripts/preprocessing/extract_frame.py
Any help would be appreciated, Thank you !

**Comment by hsiangwei0903** [comment]
Hi, yes you need to modify the extract frame code to turn videos into image so you can run our code. Unfortunately we do not support the inference on validation set for now since we use both training and validation set to train the model. You might need to modify our code and tune the parameter in order to get good performance on validation set.

**Comment by vishalsingh-11** [comment]
@hsiangwei0903 Thank you for your response, I have modified the frame extraction code to work accordingly.
