### ISSUE TITLE
Link failure

### ISSUE THREAD

**Issue by studkf** [ipl-uw/AIC23_Track1_UWIPL_ETRI#11]
[sampled dataset](https://drive.google.com/file/d/1M1I35sjOPaTWYFO4WgydqNZ9896cqQn9/view)

**Comment by hsiangwei0903** [comment]
please try this [link](https://drive.google.com/file/d/1D6qdDSz3MwH8-odNnaGIMBWkPk4w46Ng/view?usp=drive_link), thanks

**Comment by studkf** [comment]
@hsiangwei0903 thanks.
