### ISSUE TITLE
The mmyolo module of this system cannot be registered normally

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#12]
When running the Train yolov7 models on synthetic data section according to the tutorial, mmyolo gives the following warning:
Failed to search registry with scope "mmyolo" in the "log_processor" registry tree. As a workaround,  the current "log_processor" registry in "mmengine" is used to build instance. This may cause unexpected failure when  running the built modules. Please check whether "mmyolo" is a correct scope, or whether the registry is initialized.

**Comment by Sasukiii** [comment]
This means that when mmyolo was originally installed according to the mmyolo module in the project, this last step of installation was not possible:
mim install -v -e .
Please check whether it is the problem of missing modules in this system, thank you very much.

**Comment by hsiangwei0903** [comment]
We did not encounter this warning during our training, you can try to continue the training and report the training error (if there is any) to us or the mmyolo repository / or you can directly use our provided YOLOv7 model and skip the training.

**Comment by Sasukiii** [comment]
OK，I‘ll keep training.Thank you!
