### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#13]
In step 0 of the Train Synthetic ReID Model, the link to the sampled dataset is no longer valid. Hope it can be improved as soon as possible. Thank you very much!

**Comment by hsiangwei0903** [comment]
please try this [link](https://drive.google.com/file/d/1D6qdDSz3MwH8-odNnaGIMBWkPk4w46Ng/view?usp=drive_link), thanks

**Comment by Sasukiii** [comment]
Thanks！
