### ISSUE TITLE
Something went wrong in the Inferrence step

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#15]
When I follow the instructions to Get Real (S001) detection, run the following code:
bash scripts/3_inference_det_real.sh
An error will be reported:
FileNotFoundError: [Errno 2] No such file or directory:  '/root/autodl-tmp/AIC23_Track1_UWIPL_ETRI/data/test/S001/c001/img'
Is the execution of the test set missing in the frame extraction step？

**Comment by Sasukiii** [comment]
There is also why the img file is needed, the file generated by the frame should be jpg file, please tell me the solution, thank you very much.

**Comment by Sasukiii** [comment]
The 'img' required here seems to be the name of a folder, but this folder was not generated in the previous process, is there something wrong with me？

**Comment by hsiangwei0903** [comment]
The img folder refers to the folder that contains the images (in jpg format). If that folder is not named after "img", than changing the folder name into "img" should solve the problem.

**Comment by Sasukiii** [comment]
Then I know what went wrong. When you extract frame, you only extract the frames of the training set but don't extract the video frames of the test set. Is there a missing file or a missing step when you upload the project?

**Comment by Ququqq** [comment]
Hello, Hi, can you share the data set ？
