### ISSUE TITLE
Missing tools/trt.py file

### ISSUE THREAD

**Issue by studkf** [ipl-uw/AIC23_Track1_UWIPL_ETRI#17]
https://github.com/ipl-uw/AIC23_Track1_UWIPL_ETRI/blob/3ec2adeae9d393eb6ed3cdb7ded2db6d930bf0c2/BoT-SORT/tools/aic_get_detection_S001.py#L320C12-L320C76

**Comment by studkf** [comment]
Is it the same as https://github.com/Megvii-BaseDetection/YOLOX/tree/main/tools

**Comment by yangchris11** [comment]
We did not use TensorRT model (to inference) in our implementation, please considering setting it to False.

```
    if args.trt:
        assert not args.fuse, "TensorRT model is not support model fusing!"
        trt_file = osp.join(output_dir, "model_trt.pth")
        assert osp.exists(
            trt_file
        ), "TensorRT model is not found!\n Run python3 tools/trt.py first!"
        model.head.decode_in_inference = False
        decoder = model.head.decode_outputs
        logger.info("Using TensorRT to inference")
```

**Comment by studkf** [comment]
> We did not use TensorRT model (to inference) in our implementation, please considering setting it to False.
> 
> ```
>     if args.trt:
>         assert not args.fuse, "TensorRT model is not support model fusing!"
>         trt_file = osp.join(output_dir, "model_trt.pth")
>         assert osp.exists(
>             trt_file
>         ), "TensorRT model is not found!\n Run python3 tools/trt.py first!"
>         model.head.decode_in_inference = False
>         decoder = model.head.decode_outputs
>         logger.info("Using TensorRT to inference")
> ```

thanks.
