### ISSUE TITLE
spatio-temporal consistency reassignment

### ISSUE THREAD

**Issue by vishalsingh-11** [ipl-uw/AIC23_Track1_UWIPL_ETRI#19]
In the Step 4 of Run tracking - spatio-temporal consistency reassignment
` python STCRA/run_stcra.py <input_tracking_file_folder> <output_tracking_file_folder>` 

1. Could you please clarify what are the paths for `input_tracking_file_folder` and the `output_tracking_file_folder` ? 
2.  Can we perform spatio-temporal consistency reassignment, without generating the foot keypoints? I tried to do it using the clustering outputs after `run_tracking.py` and I encountered the below error.

```
Traceback (most recent call last): 
File "STCRA/run_stcra.py", line 308, in <module> 
    main() 
File "STCRA/run_stcra.py", line 288, in main 
    tracks_file_list 
  File "STCRA/run_stcra.py", line 287, in <dictcomp> 
    _track_file.split('_')[-1][:-4]: load_tracking(_track_file, enable_feet=True) for _track_file in 
  File "/home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/STCRA/file_utils.py", line 34, in load_tracking 
    assert len(values) == 16 if enable_feet else 10, f"Wrong format of tracking in {filename} with line: {line}" 
AssertionError: Wrong format of tracking in /home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001/S001_c001.txt with line: 0,1,1600.0,818.0,208.0,230.0,1.0,-1,-1,-1 
```

**Comment by vishalsingh-11** [comment]
Adding onto the above points, I also wanted to understand how the below values for HOMO variable are assigned in `STCRA/cam_utils.py` and how do I change them for my specific usecase
```
HOMO = {
    "S001": {
        "c001": np.array([[15.960967714648925, 12.641103934504969, -10836.136331862522638],
                          [-1.835398974840282, -0.998891694233460, 4826.729634388938393],
                          [0.013774024811562, -0.002497116217865, 1.000000000000000]]
                         ),
        "c002": np.array([[-0.628920333901022, -0.673555584190189, 1473.839466185914716],
                          [-0.096960410483471, 0.004922152346833, 278.717518025134211],
                          [-0.000654408791021, 0.000014246203621, 1.000000000000000]]
                         ),
        "c003": np.array([[1.132612766338583, -1.249409736401115, 755.138327271220533],
                          [-0.051440234818577, 0.161158422060954, 144.769179956926592],
                          [-0.000074135681712, -0.001257982454645, 1.000000000000000]]
                         ),
        "c004": np.array([[-10.039698157669710, -11.357587039419048, 2849.310961565047819],
                          [-1.760443892583207, 0.562101180692419, -2312.776840338349302],
                          [-0.011024040905084, 0.000566745328035, 1.000000000000000]]
                         ),
        "c005": np.array([[8.638771675710249, -13.831837080777767, -1312.458431886777362],
                          [-1.745211944767842, -1.641003052056383, -2113.002590146511466],
                          [-0.004730853927711, -0.013509625930769, 1.000000000000000]]
                         ),
        "c006": np.array([[-34.444912595614113, 30.055406684386313, 16466.787882406610152],
                          [-1.014609579389066, -2.130436599153355, 7602.048264858818584],
                          [-0.001055060502573, 0.032001140128679, 1.000000000000000]]
                         ),
        "c007": np.array([[1.699658504718583, -0.779773743762950, 186.005807766818037],
                          [0.087093078029455, 0.228593278757039, 77.925499504829929],
                          [0.000295046741868, -0.000942530317064, 1.000000000000000]]
                         )
    }
}

```

**Comment by Ququqq** [comment]
> 在运行跟踪的第 4 步中 - 时空一致性重新分配 ` python STCRA/run_stcra.py <input_tracking_file_folder> <output_tracking_file_folder>`
> 
> 1. 您能否澄清一下路径和路径是什么？`input_tracking_file_folder``output_tracking_file_folder`
> 2. 我们能否在不生成脚关键点的情况下执行时空一致性重新分配？之后我尝试使用聚类输出来执行此操作，但遇到了以下错误。`run_tracking.py`
> 
> ```
> Traceback (most recent call last): 
> File "STCRA/run_stcra.py", line 308, in <module> 
>     main() 
> File "STCRA/run_stcra.py", line 288, in main 
>     tracks_file_list 
>   File "STCRA/run_stcra.py", line 287, in <dictcomp> 
>     _track_file.split('_')[-1][:-4]: load_tracking(_track_file, enable_feet=True) for _track_file in 
>   File "/home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/STCRA/file_utils.py", line 34, in load_tracking 
>     assert len(values) == 16 if enable_feet else 10, f"Wrong format of tracking in {filename} with line: {line}" 
> AssertionError: Wrong format of tracking in /home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001/S001_c001.txt with line: 0,1,1600.0,818.0,208.0,230.0,1.0,-1,-1,-1 
> ```
Hello, I also encountered this error, may I ask you to solve it? How to solve it? Can you tell me about it? Thank you!

**Comment by vishalsingh-11** [comment]
I have not resolved the issue yet, waiting for dev's reply. @yangchris11 @hsiangwei0903 can any of you please address my error?

**Comment by yangchris11** [comment]
> In the Step 4 of Run tracking - spatio-temporal consistency reassignment ` python STCRA/run_stcra.py <input_tracking_file_folder> <output_tracking_file_folder>`
> 
> 1. Could you please clarify what are the paths for `input_tracking_file_folder` and the `output_tracking_file_folder` ?
> 2. Can we perform spatio-temporal consistency reassignment, without generating the foot keypoints? I tried to do it using the clustering outputs after `run_tracking.py` and I encountered the below error.
> 
> ```
> Traceback (most recent call last): 
> File "STCRA/run_stcra.py", line 308, in <module> 
>     main() 
> File "STCRA/run_stcra.py", line 288, in main 
>     tracks_file_list 
>   File "STCRA/run_stcra.py", line 287, in <dictcomp> 
>     _track_file.split('_')[-1][:-4]: load_tracking(_track_file, enable_feet=True) for _track_file in 
>   File "/home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/STCRA/file_utils.py", line 34, in load_tracking 
>     assert len(values) == 16 if enable_feet else 10, f"Wrong format of tracking in {filename} with line: {line}" 
> AssertionError: Wrong format of tracking in /home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001/S001_c001.txt with line: 0,1,1600.0,818.0,208.0,230.0,1.0,-1,-1,-1 
> ```

1. For the `<input_tracking_file_folder>`, it is the path of the first iteration of the tracking results you obtain from:
```
conda activate botsort_env
python tools/run_tracking.py <root_path>
```
The `output_tracking_file_folder`, is the folder you want the output to be.

2. Yes, you should be able to perform spatio-temporal consistency reassignment, without generating the foot keypoints. You might need to insert `the midpoint of the bottom edge of the bounding results` instead of the footprint results in the step:
```
python tools/convert.py
```

**Comment by vishalsingh-11** [comment]
I tried to execute is using the below command 
```
python STCRA/run_stcra.py --input_folder_name /home/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001 --output_folder_name /home/rbondili/AIC23_Track1_UWIPL_ETRI/data/SCT_re_Assigned
```

and got the following output, can you please let me know what are the specific values that I would have to change for it execute for my specific use case ? 

```
duplicate detection in /home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001/S001_c003.txt:     625/27569(2.27%) duplicate id stats [(1, 473), (4, 83), (7, 8), (10, 61)]
duplicate detection in /home/jovyan/rbondili/AIC23_Track1_UWIPL_ETRI/data/hungarian_cluster_S001/S001_c004.txt:         82/2544(3.22%) duplicate id stats [(1, 6), (7, 19), (9, 57)]
The number of duplicate ids to reassign is 1396
The number of outlier ids to reassign is 0 from 0 case1 + 0 case2
The number of duplicate ids to reassign is 1303, 1303 of them are the same as the original id
The number of outlier ids to reassign is 0 from 0 case1 + 0 case2
The number of duplicate ids to reassign is 0, 0 of them are the same as the original id
The number of outlier ids to reassign is 0 from 0 case1 + 0 case2
The number of duplicate ids to reassign is 0, 0 of them are the same as the original id
```


and can you also please comment on this  ?


> Adding onto the above points, I also wanted to understand how the below values for HOMO variable are assigned in `STCRA/cam_utils.py` and how do I change them for my specific usecase
> 
> ```
> HOMO = {
>     "S001": {
>         "c001": np.array([[15.960967714648925, 12.641103934504969, -10836.136331862522638],
>                           [-1.835398974840282, -0.998891694233460, 4826.729634388938393],
>                           [0.013774024811562, -0.002497116217865, 1.000000000000000]]
>                          ),
>         "c002": np.array([[-0.628920333901022, -0.673555584190189, 1473.839466185914716],
>                           [-0.096960410483471, 0.004922152346833, 278.717518025134211],
>                           [-0.000654408791021, 0.000014246203621, 1.000000000000000]]
>                          ),
>         "c003": np.array([[1.132612766338583, -1.249409736401115, 755.138327271220533],
>                           [-0.051440234818577, 0.161158422060954, 144.769179956926592],
>                           [-0.000074135681712, -0.001257982454645, 1.000000000000000]]
>                          ),
>         "c004": np.array([[-10.039698157669710, -11.357587039419048, 2849.310961565047819],
>                           [-1.760443892583207, 0.562101180692419, -2312.776840338349302],
>                           [-0.011024040905084, 0.000566745328035, 1.000000000000000]]
>                          ),
>         "c005": np.array([[8.638771675710249, -13.831837080777767, -1312.458431886777362],
>                           [-1.745211944767842, -1.641003052056383, -2113.002590146511466],
>                           [-0.004730853927711, -0.013509625930769, 1.000000000000000]]
>                          ),
>         "c006": np.array([[-34.444912595614113, 30.055406684386313, 16466.787882406610152],
>                           [-1.014609579389066, -2.130436599153355, 7602.048264858818584],
>                           [-0.001055060502573, 0.032001140128679, 1.000000000000000]]
>                          ),
>         "c007": np.array([[1.699658504718583, -0.779773743762950, 186.005807766818037],
>                           [0.087093078029455, 0.228593278757039, 77.925499504829929],
>                           [0.000295046741868, -0.000942530317064, 1.000000000000000]]
>                          )
>     }
> }
> ```

**Comment by yangchris11** [comment]
For homography matrix, you can refer to the following work done by Dr.Zheng:

https://github.com/zhengthomastang/Cal_PnP

The main concept is to incorporate a group of 3D points on the 3D ground level and their corresponding 2D pixel points on image coordinates. These tomography matrices are calculated through a semi-automatic selection process. For a better understanding of this, please read our paper for more information.

**Comment by yangchris11** [comment]
As for your other question, please modify `run_stcra.py` accordingly to meet your needs.
