### ISSUE TITLE
Hope to solve this problem

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#2]
Why the json file of training yolov7 has S007 data set, but the frame folder is not generated for video files in S007 data set when generating frame folder?

**Comment by yangchris11** [comment]
Hi @Sasukiii ,

Thank you for pointing out the error in our script, I had update the `DATA_METADATA` in `extract_frame.py`. This should work now.

https://github.com/ipl-uw/AIC23_Track1_UWIPL_ETRI/blob/d70e7d66a1b7ed96597d5a1a1213c0658786d1c6/scripts/preprocessing/extract_frame.py#L16

Chris

**Comment by Sasukiii** [comment]
Thanks a lot !
