### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by XIEBELL** [ipl-uw/AIC23_Track1_UWIPL_ETRI#20]
helloHello, I am very happy to see your performance in the 2023ai city challenge. You are so awesome. Could you please help share the data set? I cannot access the official website of 2023ai city challenge, thank you

**Comment by Ququqq** [comment]
Hello, have you found the data set? Can you share it？

**Comment by yangchris11** [comment]
The official dataset can be downloaded from the AI City Challenge website (https://www.aicitychallenge.org/2023-data-and-evaluation/). You need to fill the dataset request form to download them.

Referring to the DATASET LICENSE AGREEMENT from the dataset author(s), we are not allowed to share the dataset. Thank you for your understanding!

```
2.c. ... you may not copy, sell, rent, sublicense, transfer or distribute the DATASET, or share with others.  
```
