### ISSUE TITLE
why not

### ISSUE THREAD

**Issue by XIEBELL** [ipl-uw/AIC23_Track1_UWIPL_ETRI#21]

**Comment by XIEBELL** [comment]
in aic_hungarian_cluster.py line 257,you handle validation set ['005,008,013,017'],why not handle 020?
as below :
![image](https://github.com/ipl-uw/AIC23_Track1_UWIPL_ETRI/assets/77318526/dbb1c477-f3ed-4e05-b28d-1f2f51d44804)

**Comment by yangchris11** [comment]
Because the scene S020 is "office" and it is not seen in testing, so we skip it :)
