### ISSUE TITLE
MMPose Incompatibility Issue

### ISSUE THREAD

**Issue by Mian-Muhammad-AbuBakar** [ipl-uw/AIC23_Track1_UWIPL_ETRI#24]
I successfully Installed mmpose from the link: https://mmpose.readthedocs.io/en/latest/installation.html
I didn't clone the "mmpose" repo from github and installed requirements.txt from your provided codebase inside of the directory "mmpose". 

I executed only the inferencing part as per my requirement and when I try to execute the following command:
python demo/top_down_video_demo_with_track_file.py <tracking_file.txt> \ 
       configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py \
       https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \
       --video-path <video_file.mp4> \
       --out-file <out_keypoint.json>

I get the error:
(openmmlab) F:\...\AIC23_Track1_UWIPL_ETRI\mmpose>python demo/top_down_video_demo_with_track_file.py tracking_file.txt \ configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w48_coco_256x192.py \ https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth \ --video-path video_file.mp4 \ --out-file out_keypoint.json
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_track_file.py", line 11, in <module>
    from mmpose.apis import (collect_multi_frames, inference_top_down_pose_model,
  File "f:\abubakar\python_projects\aic23_track1_uwipl_etri\mmpose\mmpose\__init__.py", line 24, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==2.1.0 is used but incompatible. Please install mmcv>=1.3.8, <=1.8.0.

1) What is the issue? Even if I try to uninstall mmcv and install mmcv>=1.3.8, <=1.8.0, I get an error related to compatibility. 

2) Which versions of mmcv, mmdet and mmpose are compatible with your environment?

**Comment by lvmlvm** [comment]
Hi. I am trying to reproduce the results of this repository and I have encountered the same version problem, and it seems that you were able to fix it. Can you let me know which combo of mmcv, mmdet and mmpose you chose that could run this code successfully, and the Python and PyTorch version as well?

Many thanks.

**Comment by lvmlvm** [comment]
Ah, I was able to figure it out. For references and further reproduction, the versions are:

- Python 3.9.21
- PyTorch 2.0.1
- mmcv-full==1.7.2
- mmcv==1.6.1
- mmdet==2.25.1
- mmpose==0.29.0
