### ISSUE TITLE
Ambiguity in pose estimation and Query related to Submission

### ISSUE THREAD

**Issue by Mian-Muhammad-AbuBakar** [ipl-uw/AIC23_Track1_UWIPL_ETRI#28]
I have executed the model on the test set. The model has produced a **"submission.txt"** file along with the **output** for test detections. 

- Since the file "submission.txt" needs to be submitted on Ai City Challenge 2023 website on track-1, but as the 2023 challenge has been closed, is there any way I can predict the accuracy of my output?
-  
- During the execution of the model, I found that according to README.txt, the pose estimation commands are being executed after Anchor-Guided Clustering commands, but according to the overall pipeline diagram, they should be executed before Anchor-Guided Clustering commands. Because, if I follow README.md, the input for pose estimation would be files after Anchor-Guided Clustering, and on the other hand, if I follow the overall pipeline diagram, the input for pose estimation would be Single Camera Trackings. What is the correct sequence?

Regards,

**Comment by XIEBELL** [comment]
@Mian-Muhammad-AbuBakar  if you find  any way can predict the accuracy of output?

**Comment by Mian-Muhammad-AbuBakar** [comment]
> @Mian-Muhammad-AbuBakar if you find any way can predict the accuracy of output?

No, I didn't find any solution so far. If you have, kindly help.
