### ISSUE TITLE
Can you provide data sets?

### ISSUE THREAD

**Issue by FrankMMMMMM** [ipl-uw/AIC23_Track1_UWIPL_ETRI#4]
@hsiangwei0903 
Hello
Can you provide data sets? Links in readme can not be downloaded.
Thanks

**Comment by hsiangwei0903** [comment]
The official dataset can be downloaded from the AI City Challenge website (https://www.aicitychallenge.org/2023-data-and-evaluation/). You need to fill the dataset request form to download them.

**Comment by FrankMMMMMM** [comment]
@hsiangwei0903 
Thank you for your reply. 
I have requested, but the organizer has not replied yet. 
Can you share the dataset？

**Comment by yangchris11** [comment]
@FrankMMMMMM 

Referring to the DATASET LICENSE AGREEMENT from the dataset author(s), we are not allowed to share the dataset. So please wait for the organizer for the official approval, thank you.


`2.c. ... you may not copy, sell, rent, sublicense, transfer or distribute the DATASET, or share with others. 
`
