### ISSUE TITLE
Something Wrong

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#7]
If we follow the process of fast reproduce, skipping the optional option, the real data file would not be generated: 0324_new_offset_fixed_reassignment_iteratively_250_65_200_70_150_75_interpolation
So the last step of generating submissions.txt won't work.
Hope to reply 
Thank you.

**Comment by yangchris11** [comment]
Please adjust the output folder name in accordance with the previous step.

**Comment by Sasukiii** [comment]
OK，I‘ll try it.
