### ISSUE TITLE
inference  

### ISSUE THREAD

**Issue by mehranfvs** [ipl-uw/AIC23_Track1_UWIPL_ETRI#8]
Is it possible to obtain inferences from another video data?

**Comment by yangchris11** [comment]
Our approach is tailored to the specific data format of the AICity Challenge dataset, making it highly effective for this particular application. Adapting it for use with different video inputs is indeed possible but would necessitate a considerable amount of effort. At this time, we do not have any immediate plans to create a generic version of our Multi-Camera Tracking method, given the specialized nature of our current implementation. However, you are more than welcome to utilize our code as a starting point for your own modifications, provided that proper credit is given for our original work.

Thank you!
