### ISSUE TITLE
Would you add an overview of the project structure to the Readme

### ISSUE THREAD

**Issue by Sasukiii** [ipl-uw/AIC23_Track1_UWIPL_ETRI#9]
In fact, for beginners, although the project can be run through according to the Readme, it is difficult to innovate on this code in the face of a large project with so many modules combined. I hope that I can describe each part of the project architecture to help get started faster, thank you very much!

**Comment by hsiangwei0903** [comment]
Hello @Sasukiii , glad to hear you succesfully reproduce our work. To understand more about our overall pipeline and each module, I would suggest you take a look at our [paper](https://openaccess.thecvf.com/content/CVPR2023W/AICity/papers/Huang_Enhancing_Multi-Camera_People_Tracking_With_Anchor-Guided_Clustering_and_Spatio-Temporal_Consistency_CVPRW_2023_paper.pdf) and [video](https://drive.google.com/drive/folders/1KBXFXwhBTV7r5XZ4KJRs4bAFSOz7SoME) in the AI City Challenge workshop, and feel free to let us know if you have any further question.

**Comment by Sasukiii** [comment]
Thanks a lot! I will let you know  if i have any further question.
